### PR TITLE
Differentiate Unknown and None sex phenotype

### PR DESCRIPTION
**Pull request by Aisha-D**
- differentiate "none" and "unknown" samples

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @Aisha-D and @jethror1)

___
*[resources/home/dnanexus/reformat.py, line 117 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltJ6C_Bcmh6nrktdcV:-MltJ6C_Bcmh6nrktdcW:b-zc8rj0) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L117)):*
> ```Python
>         data (pandas data frame): Updated original_pedigree_sex column
>     """
>     original_sex_column = list(data.sex)
> ```

there is also the `.tolist()` function in pandas: https://pandas.pydata.org/docs/reference/api/pandas.Series.tolist.html

not sure if it's 'better' but just so you know it exists, I find it more readable but `list()` is fine
___
*[resources/home/dnanexus/reformat.py, line 136 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltJJAF4iWgnm5O243O:-MltJJAF4iWgnm5O243P:bddl9gy) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L136)):*
> ```Python
>                             "Check eggs_somalier_relate applet")
> 
>     print(original_sex_column)
> ```

these prints needed?
___
*[resources/home/dnanexus/reformat.py, line 139 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltJMB5Bll_clwBsFsi:-MltJMB5Bll_clwBsFsj:b64mau1) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L139)):*
> ```
> uknown
> ```

typo
___
*[resources/home/dnanexus/reformat.py, line 192 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltLkWz9kFsdL12Ld-B:-MltLkWz9kFsdL12Ld-C:b-1nmaju) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L192)):*
if you were doing this a lot or with more values I'd suggest building a dict of your values you're checking and replacing with, something like:

```
mappings={'0' : 'unknown', '1' :  'male', '2' : 'female', '3' :  'none'}

my_list = [0,1,2,3]

new_list = [mappings.get(str(x)) for x in my_list]

>>> new_list
['unknown', 'male', 'female', 'none']
```

doing it this way also means you can skip copying out and directly create the new column of data with `.apply()`:

```
>>> mappings={'0': 'unknown', '1': 'male', '2':'female', '3': 'none'}

# pointless dataframe
>>> df = pd.DataFrame([0, 1, 2, 3], columns=['A'])
>>> df
   A
0  0
1  1
2  2
3  3

# create new column of required values
>>> df['new_column'] = df['A'].apply(lambda x: mappings.get(str(x)))
>>> df
   A new_column
0  0    unknown
1  1       male
2  2     female
3  3       none

```

docs for `.apply()` and lambda functions: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html

can find examples or explain it better if you'd like, but `.apply()` in pandas is great :) 
___
*[resources/home/dnanexus/reformat.py, line 207 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltOwrV4sYN009eL4Ax:-MltOwrV4sYN009eL4Ay:b-2q0a7) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L207)):*
> ```
> Predicted_Sex
> ```
lowercase variable naming, since everything else is
___
*[resources/home/dnanexus/reformat.py, line 212 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltP4vR3u8W4yzmkQ_0:-MltP4vR3u8W4yzmkQ_1:b4pox44) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L212)):*
you can just do `for sample in reported_sex` as lists are iterable, so no need for `range()`

```
>>> my_list
[0, 1, 2, 3]
>>> for i in my_list:
...     print(i)
... 
0
1
2
3
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @jethror1)

___
*[resources/home/dnanexus/reformat.py, line 117 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltJ6C_Bcmh6nrktdcV:-Mlu3OFh2sYoah6P9Cgw:b69o2jx) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L117)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

there is also the `.tolist()` function in pandas: https://pandas.pydata.org/docs/reference/api/pandas.Series.tolist.html

not sure if it's 'better' but just so you know it exists, I find it more readable but `list()` is fine
</blockquote></details>

Don't think I was aware unless I had googled it, went for list() because of the brackets making it easier to identify the function being applied to it lol. Will note the .tolist() function
___
*[resources/home/dnanexus/reformat.py, line 136 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltJJAF4iWgnm5O243O:-Mlu3ugWCI4QeC6Wuec8:b-fmd92) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L136)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

these prints needed?
</blockquote></details>

Kept in for log reasons to know that the conversion from original_sex_column to new_pedigree_sex_column is correct
___
*[resources/home/dnanexus/reformat.py, line 139 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltJMB5Bll_clwBsFsi:-Mlu4Fas4ROW-hFKHO3s:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L139)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

> ```
> uknown
> ```

typo
</blockquote></details>

Done.
___
*[resources/home/dnanexus/reformat.py, line 192 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltLkWz9kFsdL12Ld-B:-Mlu4Y_z1REWWJrmM9Rs:bocsqrg) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L192)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

if you were doing this a lot or with more values I'd suggest building a dict of your values you're checking and replacing with, something like:

```
mappings={'0' : 'unknown', '1' :  'male', '2' : 'female', '3' :  'none'}

my_list = [0,1,2,3]

new_list = [mappings.get(str(x)) for x in my_list]

>>> new_list
['unknown', 'male', 'female', 'none']
```

doing it this way also means you can skip copying out and directly create the new column of data with `.apply()`:

```
>>> mappings={'0': 'unknown', '1': 'male', '2':'female', '3': 'none'}

# pointless dataframe
>>> df = pd.DataFrame([0, 1, 2, 3], columns=['A'])
>>> df
   A
0  0
1  1
2  2
3  3

# create new column of required values
>>> df['new_column'] = df['A'].apply(lambda x: mappings.get(str(x)))
>>> df
   A new_column
0  0    unknown
1  1       male
2  2     female
3  3       none

```

docs for `.apply()` and lambda functions: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html

can find examples or explain it better if you'd like, but `.apply()` in pandas is great :) 

</blockquote></details>

Amazing!! This is so helpful! As great as pandas is, hated converting to list and back to pandas series. Since lambda is in there going to read up on it before adding it on 
___
*[resources/home/dnanexus/reformat.py, line 207 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltOwrV4sYN009eL4Ax:-MluFyIMBQMuMORlbDDn:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L207)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

> ```
> Predicted_Sex
> ```
lowercase variable naming, since everything else is
</blockquote></details>

Done.
___
*[resources/home/dnanexus/reformat.py, line 212 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltP4vR3u8W4yzmkQ_0:-MluE4ZO4GdmQT8ecy66:bho4im8) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L212)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

you can just do `for sample in reported_sex` as lists are iterable, so no need for `range()`

```
>>> my_list
[0, 1, 2, 3]
>>> for i in my_list:
...     print(i)
... 
0
1
2
3
```
</blockquote></details>

I'm going to pull out values from two lists below and need to do it at the same position. So was using the number of items in the list to know how many times to iterate and keep select the same position in the two lists.

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @jethror1)

___
*[resources/home/dnanexus/reformat.py, line 192 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltLkWz9kFsdL12Ld-B:-MluMUAY4TN-1QYNT5NC:b-896fjx) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L192)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

Amazing!! This is so helpful! As great as pandas is, hated converting to list and back to pandas series. Since lambda is in there going to read up on it before adding it on 
</blockquote></details>

Done

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @jethror1)

___
*[resources/home/dnanexus/reformat.py, line 212 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltP4vR3u8W4yzmkQ_0:-MlumMG9EoTc42OiPodN:b-rc0adg) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L212)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

I'm going to pull out values from two lists below and need to do it at the same position. So was using the number of items in the list to know how many times to iterate and keep select the same position in the two lists.
</blockquote></details>

Used itterows instead as discussed

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Aisha-D and @jethror1)

___
*[resources/home/dnanexus/reformat.py, line 212 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4#-MltP4vR3u8W4yzmkQ_0:-Mluo6Ps6aep2ocIZDZN:b6aynjb) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/6647f21d0328c03251ef1200149eb87bdeb0c44c/resources/home/dnanexus/reformat.py#L212)):*
fyi if you need to iterate over 2 lists at the same time you can use `zip()`, this allows you to access both values in the lists at the same position together (but `iterrows() is definitely the way to go here):

```
>>> list1=[1,2,3,4,5]
>>> list2=['a','b','c','d','e']
>>> for val1, val2 in zip(list1, list2):
...     print(val1, val2)
... 
1 a
2 b
3 c
4 d
5 e
```

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
