### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Aisha-D**
Predicts sex based on x_het thresholds (default or inputted as arg)
Removed # from familyID so table appears in report
Move SampleID to first column

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1)* status: all files reviewed, 9 unresolved discussions (waiting on @Aisha-D)

___
*[dxapp.json, line 61 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUEOcJBsCY30Nkz3po:-MWUEOcK1DaBFsC3QEIW:bqxle5j) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/dxapp.json#L61)):*
> ```
>     "network": [
>       "*"
>     ]
> ```
Is network access required?
___
*[dxapp.json, line 69 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUEf8o6oUGHs2-wOoJ:-MWUEf8o6oUGHs2-wOoK:b-y9omon) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/dxapp.json#L69)):*
> ```
> "mem3_ssd1_v2_x4"
> ```
Does this need lots of memory?
mem1_ssd1_v2_x2 is likely sufficient
___
*[README.md, line 11 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUJsgp1BeBwfRRYcwr:-MWUJsgp1BeBwfRRYcws:byxfg20) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/README.md#L11)):*
> ```
> geminini
> ```
typo
I suggest removing the reference to Gemini and simply state that these are the defaults.
___
*[resources/home/dnanexus/reformat.py, line 18 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUFA4vAPo2v3dufGjt:-MWUFA4wAweTRBzYtbOx:btj39b4) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/resources/home/dnanexus/reformat.py#L18)):*
> ```
> help='default cutoff is >= 45',
> ```
Does this need to be updated? Looks like the help text from the female threshold
___
*[resources/home/dnanexus/reformat.py, line 72 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUH2d60OJRUUV0GbQZ:-MWUH2d60OJRUUV0GbQ_:b-rz1co6) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/resources/home/dnanexus/reformat.py#L72)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     else:
>         print('len(samples) =', len(samples))
>         print('len(set(samples)) =', len(set(samples)))
>         print("Duplicates sampleIDs")
> ```
</details>

Do we need to error here if duplicates are detected?
___
*[resources/home/dnanexus/reformat.py, line 79 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUHeCm5-F8Agqgl51H:-MWUHeCm5-F8Agqgl51I:by44njl) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/resources/home/dnanexus/reformat.py#L79)):*
> ```
> def get_cutoffs(args):
> ```
It's possible to set defaults within argparse
e.g.
parser.add_argument('-f', type=int, default=45)
___
*[resources/home/dnanexus/reformat.py, line 153 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUIF7M7kdqyvuQdkEW:-MWUIF7M7kdqyvuQdkEX:b-oh39uo) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/resources/home/dnanexus/reformat.py#L153)):*
> ```
>     Reported_Sex = list(data.original_pedigree_sex)
>     Predicted_Sex = list(data.Predicted_Sex)
>     Match = []
> ```
lower case for variables please
https://www.python.org/dev/peps/pep-0008/#function-and-variable-names
___
*[src/eggd_somalier_relate2multiqc.sh, line 11 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUJ42c7hTCLTTJU9Sj:-MWUJ42c7hTCLTTJU9Sk:bu6qfid) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/src/eggd_somalier_relate2multiqc.sh#L11)):*
> ```
> Value of female
> ```
For clarity:
`Value of female threshold`
___
*[src/eggd_somalier_relate2multiqc.sh, line 20 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUJYiG86jTSke6dgEn:-MWUJYiG86jTSke6dgEo:b-qqt5lk) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/src/eggd_somalier_relate2multiqc.sh#L20)):*
> ```
> find ~/in -type f -name "*" -print0 | xargs -0 -I {} mv {} ./
> ```
Is it necessary to move the files here? Can they be accessed whilst in ~/in when you call the script?

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1)* status: 2 of 6 files reviewed, 9 unresolved discussions (waiting on @mattgarner)

___
*[dxapp.json, line 61 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUEOcJBsCY30Nkz3po:-MWUNMqR3mvR0jslKq_A:b-dfldnc) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/dxapp.json#L61)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     "network": [
>       "*"
>     ]
> ```
Is network access required?
</blockquote></details>

I think it's needed for pip installing the pandas package. When network access is removed, it cant install it.
___
*[dxapp.json, line 69 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUEf8o6oUGHs2-wOoJ:-MWUNWwF3RUFjcCPFLbR:b1ec5z6) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/dxapp.json#L69)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> "mem3_ssd1_v2_x4"
> ```
Does this need lots of memory?
mem1_ssd1_v2_x2 is likely sufficient
</blockquote></details>

No, changed it to mem1_ssd1_v2_x2. Done.
___
*[README.md, line 11 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUJsgp1BeBwfRRYcwr:-MWV1dwO5G_U1fzj5G1Y:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/README.md#L11)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> geminini
> ```
typo
I suggest removing the reference to Gemini and simply state that these are the defaults.
</blockquote></details>

Done.
___
*[resources/home/dnanexus/reformat.py, line 18 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUFA4vAPo2v3dufGjt:-MWUSp7X2GjHFkN-Vm-Y:bbwrjkz) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/resources/home/dnanexus/reformat.py#L18)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> help='default cutoff is >= 45',
> ```
Does this need to be updated? Looks like the help text from the female threshold
</blockquote></details>

Forgot to change the help section -.-' Updated it now
___
*[resources/home/dnanexus/reformat.py, line 72 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUH2d60OJRUUV0GbQZ:-MWV1XzR7l7chTiZMpbq:b-5j68z0) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/resources/home/dnanexus/reformat.py#L72)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     else:
>         print('len(samples) =', len(samples))
>         print('len(set(samples)) =', len(set(samples)))
>         print("Duplicates sampleIDs")
> ```
Do we need to error here if duplicates are detected?
</blockquote></details>

Included raise exception to output errors if duplicates
___
*[resources/home/dnanexus/reformat.py, line 79 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUHeCm5-F8Agqgl51H:-MWV1lJ8B0CPDD-ySJvZ:b-4ze6t3) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/resources/home/dnanexus/reformat.py#L79)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> def get_cutoffs(args):
> ```
It's possible to set defaults within argparse
e.g.
parser.add_argument('-f', type=int, default=45)
</blockquote></details>

Done. Yujin's tutorial helped !
___
*[resources/home/dnanexus/reformat.py, line 153 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUIF7M7kdqyvuQdkEW:-MWV1tHL3E9TbxTiT74x:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/resources/home/dnanexus/reformat.py#L153)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     Reported_Sex = list(data.original_pedigree_sex)
>     Predicted_Sex = list(data.Predicted_Sex)
>     Match = []
> ```
lower case for variables please
https://www.python.org/dev/peps/pep-0008/#function-and-variable-names
</blockquote></details>

Done.
___
*[src/eggd_somalier_relate2multiqc.sh, line 11 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUJ42c7hTCLTTJU9Sj:-MWV1u47ClvZ0uf19bLt:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/src/eggd_somalier_relate2multiqc.sh#L11)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> Value of female
> ```
For clarity:
`Value of female threshold`
</blockquote></details>

Done.
___
*[src/eggd_somalier_relate2multiqc.sh, line 20 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUJYiG86jTSke6dgEn:-MWV1uhQ2dEMblsj3bA9:bfmy8wn) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/src/eggd_somalier_relate2multiqc.sh#L20)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> find ~/in -type f -name "*" -print0 | xargs -0 -I {} mv {} ./
> ```
Is it necessary to move the files here? Can they be accessed whilst in ~/in when you call the script?
</blockquote></details>

Used mv command instead since its one file. 
Because the output filename depends on input argument and appends 'Multiqc' before it, the input can't have /in

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1)* status: all files reviewed, 7 unresolved discussions (waiting on @Aisha-D)

___
*[dxapp.json, line 61 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUEOcJBsCY30Nkz3po:-MWyRvCW7IWUcftq4WL9:b-onv3fl) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/dxapp.json#L61)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

I think it's needed for pip installing the pandas package. When network access is removed, it cant install it.
</blockquote></details>

As we discussed, we will tweak the app to remove external dependencies
___
*[README.md, line 6 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWySruR0q3lGPM1VuiO:-MWySruR0q3lGPM1VuiP:brzxc71) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/README.md#L6)):*
> ```
> https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/dev/Somalier_relate2multiqc_workflow.jpg
> ```
Image path should be relative to repo root, not URL
___
*[resources/home/dnanexus/reformat.py, line 24 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWyT1_u27sup2jKfSwu:-MWyT1_u27sup2jKfSwv:b-aloho2) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/resources/home/dnanexus/reformat.py#L24)):*
> ```
> An integer value for het calls threshold for females
> ```
Is female more than or less than the threshold?
Could you enforce that the values provided are ints via argparse?
___
*[resources/home/dnanexus/reformat.py, line 33 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWyT6Vn1aaY_tRoJx-Y:-MWyT6Vn1aaY_tRoJx-Z:b-26cheo) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/resources/home/dnanexus/reformat.py#L33)):*
> ```
> An integer value for het calls threshold for males.
> ```
Is male more than or less than the threshold?
Could you enforce that the values provided are ints via argparse?
___
*[resources/home/dnanexus/reformat.py, line 101 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWyU23GE0fEGx9uzi7C:-MWyU23GE0fEGx9uzi7D:b-wpmhez) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/resources/home/dnanexus/reformat.py#L101)):*
> ```
>     f_cutoff = int(f_cutoff)
>     m_cutoff = int(m_cutoff)
> ```
See previous comment about argparse enforcing ints
___
*[resources/home/dnanexus/reformat.py, line 150 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWyUYkA363K3Gd7aLs7:-MWyUYkA363K3Gd7aLs8:b-xf2gk2) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/resources/home/dnanexus/reformat.py#L150)):*
> ```
> 0,l
> ```
Space after , for pep8 compliance please
___
*[resources/home/dnanexus/reformat.py, line 156 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWyUoX481X6orXjlXKl:-MWyUoX481X6orXjlXKm:b-8wvrim) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/resources/home/dnanexus/reformat.py#L156)):*
> ```
> apply·
> ```
trailing whitespace - pep8 compliance

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1)* status: all files reviewed, 7 unresolved discussions (waiting on @Aisha-D and @mattgarner)

___
*[dxapp.json, line 61 at r2](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWUEOcJBsCY30Nkz3po:-MX2YaGy7s5UlV9FJ5j4:b-4g9ql8) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/a87fa32494c75528002651a0bc86917de188808b/dxapp.json#L61)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

As we discussed, we will tweak the app to remove external dependencies
</blockquote></details>

Done. Included dependencies so no network is needed. 
___
*[resources/home/dnanexus/reformat.py, line 24 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWyT1_u27sup2jKfSwu:-MX2bocR7KAUE6Iphsi5:bpktgl1) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/resources/home/dnanexus/reformat.py#L24)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> An integer value for het calls threshold for females
> ```
Is female more than or less than the threshold?
Could you enforce that the values provided are ints via argparse?
</blockquote></details>

Done. Included type=int when parsing. It assigns samples as female if they are equal to or more than the value provided. 
___
*[resources/home/dnanexus/reformat.py, line 33 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWyT6Vn1aaY_tRoJx-Y:-MX2eHGk48Ib4_4HRhCx:b88gqu0) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/resources/home/dnanexus/reformat.py#L33)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> An integer value for het calls threshold for males.
> ```
Is male more than or less than the threshold?
Could you enforce that the values provided are ints via argparse?
</blockquote></details>

Done. Included type=int when parsing. It assigns samples as male if they are equal to or less than the value provided. 
___
*[resources/home/dnanexus/reformat.py, line 101 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWyU23GE0fEGx9uzi7C:-MX2eJoHAS-BaMhUON89:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/resources/home/dnanexus/reformat.py#L101)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     f_cutoff = int(f_cutoff)
>     m_cutoff = int(m_cutoff)
> ```
See previous comment about argparse enforcing ints
</blockquote></details>

Done.
___
*[resources/home/dnanexus/reformat.py, line 150 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWyUYkA363K3Gd7aLs7:-MX2eezDE4xgL722XcJZ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/resources/home/dnanexus/reformat.py#L150)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> 0,l
> ```
Space after , for pep8 compliance please
</blockquote></details>

Done.
___
*[resources/home/dnanexus/reformat.py, line 156 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWyUoX481X6orXjlXKl:-MX2ejLd7m-VGC1jfbs3:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/resources/home/dnanexus/reformat.py#L156)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> apply·
> ```
trailing whitespace - pep8 compliance
</blockquote></details>

Done.

**Review by mattgarner — APPROVED** [review]
> Reviewed 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

___
*[README.md, line 6 at r3](https://reviewable.io/reviews/eastgenomics/eggd_somalier_relate2multiqc/1#-MWySruR0q3lGPM1VuiO:-MXC-Q267PC5Sg_KObSE:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/1bd76407e9db5d287e0a878531a18614c1b5f8dd/README.md#L6)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> https://github.com/eastgenomics/eggd_somalier_relate2multiqc/blob/dev/Somalier_relate2multiqc_workflow.jpg
> ```
Image path should be relative to repo root, not URL
</blockquote></details>

Done

**Pull request merged**
